version: "3.1"

services:
    nginx_dev:
        image: nginx
        container_name: nginx_proxy
        restart: always
        ports:
            - 8080:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app
        networks:
            - network

    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: project
        container_name: project
        restart: always
        ports:
            - 3000:3000
        networks:
            - network

    mongo:
        image: mongo
        container_name: mongo
        restart: always
        ports:
            - 27017:27017
        networks:
            - network

networks:
  network:
    driver: bridge
